name: hiwayda_oracion_islamica
description: this app used to learn muslims how to pray
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  dartz: ^0.10.1
  logger: ^2.0.2+1
  number_paginator: ^0.4.1
  internet_connection_checker: ^1.0.0+1
  loading_animation_widget: ^1.2.0+4
  flutter_easyloading: ^3.0.5
  font_awesome_flutter: ^10.6.0
  flutter_screenutil: ^5.9.0
  multi_select_flutter: ^4.1.3
  dropdown_button2: ^2.3.9
  shimmer: ^3.0.0
  intl:
  shared_preferences: ^2.2.0
  dio: ^5.3.2
  provider: ^6.0.5
  flutter_svg:
#  pinput:
  cached_network_image: ^3.2.3
  pretty_dio_logger: ^1.3.1
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.11
  #assets_audio_player: ^3.1.1
  video_player: ^2.7.1
  dots_indicator: ^2.1.0
  page_view_dot_indicator: ^2.3.0
  adhan_dart:
  timezone:
  connectivity_plus: ^2.3.9
  geolocator: ^9.0.2
#  #flutter_qiblah: ^2.0.0
#  #location:
  location: ^5.0.3
  flutter_compass:
  jhijri: ^0.0.1
  timer_builder: ^2.0.0
  flutter_archive:
  flutter_launcher_icons: ^0.13.1
  flutter_linkify: ^6.0.0
  just_audio: ^0.9.37
  webview_flutter: ^4.7.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  percent_indicator: ^4.2.3
  open_file: ^3.3.2
  # share_plus: ^9.0.0
  audioplayers: ^6.0.0
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21


flutter:

  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/
    - assets/svg/
    - assets/
    - assets/json/
    - assets/audio/
    - assets/video/
    - assets/svg/icons/
    - assets/svg/images/
    - assets/Json.zip
    - assets/books/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 900
